<?php
require_once __DIR__ . '/../bootstrap.php'; require_method('POST'); $u=require_auth(['super_admin']); require_csrf(); $d=request_json();
$bid=(int)($d['business_id']??0);$mode=trim((string)($d['mode']??'post'));$brief=trim((string)($d['brief']??''));
$st=db()->prepare('SELECT * FROM businesses WHERE id=?');$st->execute([$bid]);$b=$st->fetch();if(!$b)json_response(['ok'=>false,'error'=>'Business not found'],404);
$kq=db()->prepare('SELECT keyword,category,priority FROM keywords WHERE business_id=? AND is_active=1 ORDER BY priority DESC LIMIT 30');$kq->execute([$bid]);$k=$kq->fetchAll();$kw=implode(', ',array_column($k,'keyword'));
$modePrompts=[
'post'=>'Create a Google Business Profile post plan. Return a short headline, a natural 120-220 word post, 1 CTA suggestion, and 3 image ideas.',
'photo'=>'Create a photo update plan for Google Business Profile. Return 8 photo ideas, recommended filenames, short captions, and what each photo should prove to a customer.',
'services'=>'Create a clean service-list draft suitable for a Google Business Profile. Return 8-12 service names, 1-line descriptions, and suggested grouping. Only propose services that are strongly implied by the business category/description/keywords.',
'products'=>'Create a product/catalog content plan for the business. Return 8 product or category ideas with customer-friendly titles and descriptions. Clearly label this as a manual catalog plan, not an API product-post payload.',
'ranking'=>'Create a practical local visibility action plan covering profile completeness, categories, services, photos, posts, review response habits, NAP consistency, website/local pages and measurement. Do not promise rankings.',
'review_reply'=>'Create 5 reusable merchant review-reply templates: positive, detailed positive, neutral, complaint, and no-text review. Keep them human and brand-appropriate.'
];
if(!isset($modePrompts[$mode]))json_response(['ok'=>false,'error'=>'Unsupported AI tool'],422);
$prompt="You are GrowReview's Google Business Profile optimisation assistant. Business: {$b['name']}. Category: ".($b['category']?:'not specified').". City: ".($b['city']?:'not specified').". Description: ".($b['description']?:'not provided').". High-priority keyword context: {$kw}. Extra brief: {$brief}. Task: {$modePrompts[$mode]} Use natural language, avoid keyword stuffing, avoid unverifiable claims, and make recommendations specific to this business. Return concise markdown only.";
$api=envv('GEMINI_API_KEY','');if(!$api)json_response(['ok'=>false,'error'=>'GEMINI_API_KEY is not configured'],500);$model=envv('GEMINI_MODEL','gemini-2.5-flash');$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent';$payload=['contents'=>[['parts'=>[['text'=>$prompt]]]],'generationConfig'=>['temperature'=>.9,'topP'=>.95,'maxOutputTokens'=>1200]];$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','x-goog-api-key: '.$api],CURLOPT_POSTFIELDS=>json_encode($payload),CURLOPT_TIMEOUT=>25]);$raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if(!$raw||$code<200||$code>=300)json_response(['ok'=>false,'error'=>'AI generation failed'],502);$j=json_decode($raw,true);$text=trim((string)($j['candidates'][0]['content']['parts'][0]['text']??''));if($text==='')json_response(['ok'=>false,'error'=>'AI returned an empty response'],502);json_response(['ok'=>true,'content'=>$text,'business'=>$b['name'],'mode'=>$mode]);
