import Link from "next/link";
import Image from "next/image";

const faqs = [
 ["What is GMBSPYS?", "GMBSPYS is a business prospecting workspace designed to help organize business information, searches and leads gathered through its supported workflow."],
 ["How do I get started?", "Set up the GMBSPYS extension and account, run a relevant business search, then review and organize available results in your dashboard."],
 ["Can I export business data?", "The dashboard is designed for structured lead review and export. Export availability depends on the features and data connected to your account."],
 ["Does GMBSPYS guarantee Google rankings or leads?", "No. GMBSPYS is a workflow tool. Results depend on your targeting, data quality, outreach practices and applicable platform rules."],
 ["How should I use collected data?", "Use data responsibly, respect privacy and applicable marketing laws, and follow Google Maps and other relevant platform terms."],
];
const schema = {"@context":"https://schema.org","@type":"SoftwareApplication","name":"GMBSPYS","applicationCategory":"BusinessApplication","operatingSystem":"Web browser","description":"Business prospecting and lead management workspace for organizing local business information."};
const faqSchema = {"@context":"https://schema.org","@type":"FAQPage","mainEntity":faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
export default function Home(){return <>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
 <header className="site-nav"><Link className="brand" href="/"><span className="brandmark">G</span> <span>GMBSPYS</span></Link><nav className="navlinks"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#guides">Guides</a><a href="#faq">FAQ</a><Link className="btn" href="/dashboard">Open dashboard ↗</Link></nav></header>
 <main><section className="hero"><div><span className="eyebrow"><span className="dot" style={{background:"#34a853"}}/> BUSINESS PROSPECTING WORKSPACE</span><h1>Turn local business research into <span>organized leads.</span></h1><p>Discover a clearer workflow for finding, reviewing and managing local business prospects. Bring your research together in one place with GMBSPYS.</p><div className="actions"><Link className="btn" href="/dashboard">Explore dashboard →</Link><a className="btn secondary" href="#how-it-works">See how it works</a></div><div className="trust"><span>✓ Search workflow</span><span>✓ Lead organization</span><span>✓ Export-ready workspace</span></div></div>
 <div className="hero-art"><div className="art-glow"/><Image src="/gmbspys-hero.png" alt="Illustration of a business lead dashboard, local map pins and analytics" width={1536} height={1024} priority className="hero-image"/><div className="floating-note note-one"><span className="mini-dot green"/> <span><b>Find prospects</b><small>Keep local research organized</small></span></div><div className="floating-note note-two"><span className="mini-dot yellow"/> <span><b>Google-inspired design</b><small>Simple, clear, lightweight</small></span></div></div></section>
 <section className="section section-feature" id="features"><div className="section-kicker">BUILT FOR LOCAL PROSPECTING</div><h2>A practical workflow, from search to follow-up</h2><p className="section-intro">Keep business records, prospect notes and research history organized instead of scattered across tabs and spreadsheets.</p><div className="featuregrid"><article className="feature"><div className="feature-icon blue-icon">⌕</div><h3>Business research</h3><p>Collect and review business details through your configured GMBSPYS workflow, with a consistent place to revisit results.</p></article><article className="feature"><div className="feature-icon red-icon">◎</div><h3>Lead management</h3><p>Organize prospects, track lead status and keep useful notes alongside business records.</p></article><article className="feature"><div className="feature-icon green-icon">↗</div><h3>Useful exports</h3><p>Prepare business information for a team workflow or spreadsheet when export features and permissions are available.</p></article></div></section>
 <section className="section" id="how-it-works"><h2>How GMBSPYS works</h2><p className="section-intro">A simple three-stage process to keep prospecting structured.</p><div className="steps"><article className="step"><div className="stepnum">STEP 01</div><h3>Find relevant businesses</h3><p>Choose a relevant category and location, and run your supported research workflow.</p></article><article className="step"><div className="stepnum">STEP 02</div><h3>Review and qualify</h3><p>Check business details, remove irrelevant prospects and add notes or lead status where supported.</p></article><article className="step"><div className="stepnum">STEP 03</div><h3>Organize your next action</h3><p>Use your dashboard and exports to manage follow-up while respecting privacy and platform terms.</p></article></div></section>
 <section className="section" id="guides"><h2>GMBSPYS guides and resources</h2><p className="section-intro">Start with the basics, then build a repeatable local business prospecting process.</p><div className="featuregrid"><article className="feature"><div className="feature-icon">⌘</div><h3>Setup guide</h3><p>Learn the core setup sequence, connect your account and verify the dashboard workflow.</p><Link href="/guides/getting-started" style={{color:"#1a73e8",fontWeight:700}}>Read getting started →</Link></article><article className="feature"><div className="feature-icon">▤</div><h3>Lead quality checklist</h3><p>Use category relevance, contact completeness and location fit to review prospects.</p><Link href="/guides/lead-quality" style={{color:"#1a73e8",fontWeight:700}}>Read the checklist →</Link></article><article className="feature"><div className="feature-icon">♧</div><h3>Responsible data use</h3><p>Understand why platform rules, privacy obligations and careful outreach matter.</p><Link href="/guides/responsible-use" style={{color:"#1a73e8",fontWeight:700}}>Read the guide →</Link></article></div></section>
 <section className="section faq" id="faq"><h2>Frequently asked questions</h2><p className="section-intro">Quick answers about the GMBSPYS workflow.</p>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 <section className="section"><div className="notice"><strong>Important:</strong> GMBSPYS does not guarantee business contact accuracy, lead conversion or search-engine rankings. Verify records before use and follow applicable laws and third-party platform terms.</div></section></main>
 <footer className="footer"><div className="footer-inner"><div><strong style={{color:"white"}}>GMBSPYS</strong><p>Business research. Better organized.</p></div><div style={{display:"flex",gap:18,flexWrap:"wrap"}}><Link href="/dashboard">Dashboard</Link><Link href="/businesses">Businesses</Link><Link href="/guides/getting-started">Guides</Link><Link href="/admin">Admin</Link></div><span>© {new Date().getFullYear()} GMBSPYS</span></div></footer>
 </>}
